# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 编译 & 构建

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14]

    steps:
    - uses: actions/checkout@v2
    - name: 设置NodeJS版本为 ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install yarn && yarn install
    - run: yarn run docs:build

    - name: 上传文件到 ${{ secrets.IP }} 
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: '${{ secrets.IP }}'
        port: 22
        username: 'ubuntu'
        password: '${{ secrets.PASSWORD }} '
        localDir:  './dist/*'
        remoteDir: '/tmp/dist'